package com.seleniumtutorial;

import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class Project_2 {
public static void main(String[] args) throws IOException {
	System.setProperty("webdriver.chrome.driver", 
			"C:\\Users\\ELCOT\\eclipse-workspace\\Mydemo\\Browser\\chromedriver.exe");
	WebDriver d = new ChromeDriver();
	d.get("http://automationpractice.com/index.php");
	d.manage().window().maximize();
	d.manage().timeouts().implicitlyWait(55, TimeUnit.SECONDS);
	Actions a= new Actions(d);
	WebElement w = d.findElement(By.xpath("//a[@title='Women']"));
	a.moveToElement(w).build().perform();
	WebElement c = d.findElement(By.xpath("(//a[@title='Casual Dresses'])[1]"));
	c.click();
	WebElement m = d.findElement(By.xpath("//div[@class='right-block']"));
	a.moveToElement(m).build().perform();
	WebElement b = d.findElement(By.xpath("//a[@title='Add to cart']"));
	b.click();
	WebElement e = d.findElement(By.xpath("//a[@class='btn btn-default button button-medium']"));
	e.click();
	WebElement h = d.findElement(By.xpath("//input[@size='2']"));
	h.clear();
	h.sendKeys("7");
	WebElement k = d.findElement(By.xpath("(//a[@title='Proceed to checkout'])[2]"));
	k.click();
//	WebElement mail = d.findElement(By.xpath("(//input[@type='text'])[2]"));
//	mail.sendKeys("kingmanitoy@gmail.com");
//	WebElement n = d.findElement(By.id("SubmitCreate"));
//	n.click();
//	WebElement o = d.findElement(By.xpath("(//input[@type='radio'])[1]"));
//	o.click();
//	WebElement name = d.findElement(By.xpath("//input[@id='customer_firstname']"));
//	name.sendKeys("Manikandan");
//	WebElement last = d.findElement(By.xpath("//input[@id='customer_lastname']"));
//	last.sendKeys("Arjunan");
//	WebElement pass = d.findElement(By.id("passwd"));
//	pass.sendKeys("manikandan");
//	WebElement day = d.findElement(By.id("days"));
//	Select s1 = new Select(day);
//	s1.selectByValue("12");
//	WebElement mon = d.findElement(By.id("months"));
//	Select s2 = new Select(mon);
//	s2.selectByValue("12");
//	WebElement yr = d.findElement(By.id("years"));
//	Select s3 = new Select(yr);
//	s3.selectByValue("1995");
//	WebElement com = d.findElement(By.id("company"));
//	com.sendKeys("XYZ company");
//	WebElement add = d.findElement(By.id("address1"));
//	add.sendKeys("Choolaimedu");
//	WebElement add2 = d.findElement(By.id("address2"));
//	add2.sendKeys("Nungampakkam");
//	WebElement city = d.findElement(By.id("city"));
//	city.sendKeys("Chennai");
//	WebElement stat = d.findElement(By.xpath("//select[@name='id_state']"));
//	Select s4 = new Select(stat);
//	s4.selectByIndex(7);
//	WebElement code = d.findElement(By.id("postcode"));
//	code.sendKeys("00004");
//	WebElement ct = d.findElement(By.xpath("//select[@name='id_country']"));
//	Select s5 = new Select(ct);
//	s5.selectByValue("21");
//	WebElement ot = d.findElement(By.id("other"));
//	ot.sendKeys("Hi, Hello");
//	WebElement ph = d.findElement(By.id("phone"));
//	ph.sendKeys("5367281938");
//	WebElement num = d.findElement(By.xpath("//input[@id='phone_mobile']"));
//	num.sendKeys("6475985368");
//	WebElement aa = d.findElement(By.id("alias"));
//	aa.clear();
//	aa.sendKeys("Nungampakkam");
//	WebElement sub = d.findElement(By.id("submitAccount"));
//	sub.click();
	WebElement mail = d.findElement(By.id("email"));
	mail.sendKeys("kingmanitoy@gmail.com");
	WebElement pas = d.findElement(By.id("passwd"));
	pas.sendKeys("manikandan");
	WebElement lin = d.findElement(By.id("SubmitLogin"));
	lin.click();
	WebElement bu = d.findElement(By.xpath("(//button[@type='submit'])[2]"));
	bu.click();
	WebElement che = d.findElement(By.id("cgv"));
	che.click();
	WebElement cli = d.findElement(By.xpath("(//button[@type='submit'])[2]"));
	cli.click();
	WebElement cheq = d.findElement(By.xpath("//a[@class='cheque']"));
	cheq.click();
	WebElement submit = d.findElement(By.xpath("(//button[@type='submit'])[2]"));
	submit.click();
	TakesScreenshot ts = (TakesScreenshot)d;
	File sc = ts.getScreenshotAs(OutputType.FILE);
	File file = new File("C:\\Users\\ELCOT\\eclipse-workspace\\Selenium\\ScrnShot\\project2.png");
	FileUtils.copyFile(sc, file);
}
}
